"""Remotion render orchestration, props preparation, and assemble."""

from app.video.render.status import (  # noqa: F401
    DEFAULT_FRAME_RATE,
    RenderTimeoutError,
    CaptureDurationError,
    RecordingProvenanceError,
    _validate_recording_provenance,
    _completed_segment_after_timeout,
    _segment_is_complete,
    _run_remotion_segment,
    _render_concurrency,
    _render_timeout_seconds,
    _remotion_setup_timeout_ms,
    _remotion_hardware_acceleration,
    _render_chunk_frames,
    NarrationTimingError,
)
from app.video.render.remotion_props import (  # noqa: F401
    _prepare_remotion_source,
    _frame_rate,
    _PRESENTATION_SECRET_TERMS,
    _presentation_secret_redactions,
    _outro_copy,
    _recording_space_rect,
    _recording_space_cursor_paths,
    _safe_camera_zoom,
    _editorial_cut_windows,
    _remap_trace_for_cuts,
    _build_editorial_source,
    _evidence_timed_beat_ranges,
    _evidence_timed_captions,
)
from app.video.render.assemble import (  # noqa: F401
    render_remotion,
    _promote_render,
)

__all__ = [
    "DEFAULT_FRAME_RATE",
    "RenderTimeoutError",
    "CaptureDurationError",
    "RecordingProvenanceError",
    "_validate_recording_provenance",
    "_completed_segment_after_timeout",
    "_segment_is_complete",
    "_run_remotion_segment",
    "_render_concurrency",
    "_render_timeout_seconds",
    "_remotion_setup_timeout_ms",
    "_remotion_hardware_acceleration",
    "_render_chunk_frames",
    "NarrationTimingError",
    "_prepare_remotion_source",
    "_frame_rate",
    "_PRESENTATION_SECRET_TERMS",
    "_presentation_secret_redactions",
    "_outro_copy",
    "_recording_space_rect",
    "_recording_space_cursor_paths",
    "_safe_camera_zoom",
    "_editorial_cut_windows",
    "_remap_trace_for_cuts",
    "_build_editorial_source",
    "_evidence_timed_beat_ranges",
    "_evidence_timed_captions",
    "render_remotion",
    "_promote_render",
]
